In [ ]:
import pythreejs as three
from ipywidgets import *
import numpy as np
import util

ModuleNotFoundError: No module named 'util'

In [ ]:
env = util.Environment()

b = three.Group()
k = util.create_axes(3, show_labels=True, name="K")

rectangle = util.create_quad([0,0,0],4,2,3)
k.add(rectangle)
b.add(k)

mat = np.array([                        #für die Orientierung des körpereigenen Koordinatensystems
    [ 0,  0, -1],
    [-1,  0,  0],
    [ 0,  1,  0]
])
euler = util.rot_matrix_to_euler(mat, "XYZ")
env.add(b)

util.translate(k, [3, 4, 0])            #Das körpereigene Koordinatensystem im Bezug auf das Basiskoordinatensystem verschieben
util.translate(rectangle, [2, 1, 1.5])  #Den Quader im Bezug auf das körpereigene Koordinatensystem richtig verschieben

display(env)
util.rotate(k, euler, "XYZ")

angles=[60, -180, -90]
order = "ZXY"
util.set_rotation(b, [0,0,0], order)
util.rotate_global_animated(b, angles, order)

util.set_rotation(b, [0,0,0], order)
util.rotate_animated(b, angles[::-1], order[::-1])


Renderer(camera=PerspectiveCamera(aspect=1.4, position=(8.0, 8.0, 8.0), projectionMatrix=(1.0, 0.0, 0.0, 0.0, …

In [ ]:
rot_mat_x = np.array([[1, 0, 0],
    [0, np.cos(np.radians(-180)), -np.sin(np.radians(-180))],
    [0, np.sin(np.radians(-180)), np.cos(np.radians(-180))]
    ])

rot_mat_y = np.array([
    [np.cos(np.radians(-90)), 0, np.sin(np.radians(-90))],
    [0, 1, 0],
    [-np.sin(np.radians(-90)), 0, np.cos(np.radians(-90))]
    ])

rot_mat_z = np.array([
    [np.cos(np.radians(60)), -np.sin(np.radians(60)), 0],
    [np.sin(np.radians(60)),  np.cos(np.radians(60)), 0],
    [0,             0,             1]
    ])

rot_mat_ges = rot_mat_y @ rot_mat_x @ rot_mat_z

util.set_rotation(b, [0,0,0], order)
util.apply_rot_matrix_animated(b, rot_mat_ges)

print(rot_mat_ges, "Gesamtrotationsmatrix\n")
print(mat, "Rotation als Matrix vor der Drehung\n")
print(util.rot_matrix_to_euler(mat), "Rotation als ZYZ-Eulerwinkel\n")
print(rot_mat_ges @ mat, "Rotation als Matrix nach der Drehung\n")
print(util.rot_matrix_to_euler(rot_mat_ges @ mat, "ZYX"), "Roll Nick Gier Winkel")

[[ 1.36673694e-16  8.20357802e-18  1.00000000e+00]
 [-8.66025404e-01 -5.00000000e-01  1.22464680e-16]
 [ 5.00000000e-01 -8.66025404e-01 -6.12323400e-17]] Gesamtrotationsmatrix

[[ 0  0 -1]
 [-1  0  0]
 [ 0  1  0]] Rotation als Matrix vor der Drehung

[-180.   90.   90.] Rotation als ZYZ-Eulerwinkel

[[-8.20357802e-18  1.00000000e+00 -1.36673694e-16]
 [ 5.00000000e-01  1.22464680e-16  8.66025404e-01]
 [ 8.66025404e-01 -6.12323400e-17 -5.00000000e-01]] Rotation als Matrix nach der Drehung

[ 90. -60. 180.] Roll Nick Gier Winkel
